# Generated by Django 3.1.6 on 2021-03-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=120, verbose_name='Team Name')),
                ('member1', models.CharField(max_length=300)),
                ('member1_phone', models.CharField(blank=True, max_length=25, verbose_name='Member1 Phone')),
                ('member2', models.CharField(max_length=300)),
                ('member2_phone', models.CharField(blank=True, max_length=25, verbose_name='Member2 Phone')),
                ('member3', models.CharField(max_length=300)),
                ('member4', models.CharField(max_length=300)),
                ('member3_phone', models.CharField(blank=True, max_length=25, verbose_name='Member3 Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
